### ISSUE TITLE
Please help !!! How to use your package 

### ISSUE THREAD

**Issue by IronMan756** [SoftwareBrothers/admin-bro-nestjs#2]

**Comment by wojtek-krysiak** [comment]
hi. sorry for late response. take a look at the beta branch, which corresponds to @admin-bro/nestjs@beta npm tag. Documentation is here https://github.com/SoftwareBrothers/admin-bro-nestjs/blob/beta/src/index.ts

but you have to install it with yarn add @admin-bro/nestjs@beta
