### ISSUE TITLE
Problem using admin-bro-nestjs (or admin-bro-typeorm) without ActiveRecord pattern

### ISSUE THREAD

**Issue by islerfab** [SoftwareBrothers/admin-bro-nestjs#8]
Hi guys,

Thanks a lot for your work, AdminBro looks like a super-useful addition to my project. I've set it up correctly, I assume; Without adding the resources (Entities), the admin page loads fine, including trivial authorization etc.
When I add the resources, I get the following error (and as you can see below, I'm registering the adapter):
```
UnhandledPromiseRejectionWarning: NoResourceAdapterError: There are no adapters supporting one of the resource you provided
    at resources.map.rawResource (<...>/node_modules/admin-bro/lib/backend/utils/resources-factory/resources-factory.js:99:15)
```

When I was digging a bit deeper, I found that in `Resource.ts` of `admin-bro-typeorm`, the entities are expected to have a repository attached (`getRepository()`), thus to be children of the BaseEntity, which means it's assumed that the project is using the ActiveRecord pattern (https://typeorm.io/#/active-record-data-mapper). Unfortunately, in my project I am forced to use the Data Mapper pattern. Am I making a wrong observation / assumption on the way until here?

If not: Is there a workaround for this, e.g. using the `createAdminAsync(...)` method, or is this going too deep and is probably an issue to raise in the `admin-bro-typeorm` repository?
If there is no workaround, that would be very unfortunate of course, since I would love to use it in this project, but in that case I think some documentation about this would make sense.

Thanks a lot in advance!

My code:

```ts
import { Module } from "@nestjs/common";
import { TypeOrmModule } from "@nestjs/typeorm";

import { User } from "../database/entities/user.entity";

import { AdminModule } from "@admin-bro/nestjs";
import { Database, Resource } from "@admin-bro/typeorm";
import { validate } from "class-validator";
import AdminBro from "admin-bro";

Resource.validate = validate;
AdminBro.registerAdapter({ Database, Resource });

@Module({
  imports: [
    TypeOrmModule.forRoot(),
    AdminModule.createAdmin({
      adminBroOptions: {
        rootPath: "/admin",
        resources: [ User ],
      },
      auth: {
        authenticate: async (email, password) => Promise.resolve({ email: "test" }),
        cookieName: "test",
        cookiePassword: "testPass",
      },
    })
  ],
  controllers: [],
})
export class AppModule {}
```

**Comment by SimonB407** [comment]
Hi, sorry that you had to wait so long for answer. It looks like `@admin-bro/typeorm` module problem. Please report an issue there. Also you can join our [Slack](https://join.slack.com/t/adminbro/shared_invite/zt-djsqxxpz-_YCS8UMtQ9Ade6DPuLR7Zw), there is a chance that someone will help you there.
